#!/usr/bin/env bash
#  nginx listens to port 80 only

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
echo "" | sudo dd status=none of=/run/nginx.pid

