#!/usr/bin/env bash
#bash to installs the 'ufw' firewall and,
#rules on 'web-01'

apt-get install ufw -y
ufw default deny incoming
ufw default allow outgoing
ufw allow 22
ufw allow 443
ufw allow 80
ufw enable 
